language: ruby
rvm:
  - 2.5.0
env: 
  - MOZ_HEADLESS=1
addons:
  firefox: latest
before_script:
  - mysql -e 'create database stizun_test;'
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_install:
  - "sudo apt-get update"
  - "sudo apt-get install sphinxsearch"
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.19.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
bundler_args: --without development
# uncomment this line if your project needs to run something other than `rake`:
script: ./script/run_tests.sh
