language: ruby
rvm:
  - 1.9.2
before_script:
  - mysql -e 'create database stizun_test;'
bundler_args: --without development
# uncomment this line if your project needs to run something other than `rake`:
script: bundle exec rake stizun:test 
