language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - jruby-head
env: DISPLAY=:99.0
before_script:
  - mysql -e 'create database stizun_test;'
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
bundler_args: --without development
# uncomment this line if your project needs to run something other than `rake`:
script: bundle exec rake stizun:test 
