production:
  default_from_email: "info@lincomp.ch"
  email_subject_prefix: "[Lincomp]"
development:
  default_from_email: "root@localhost"
  email_subject_prefix: "[Local Shop]"
test:
  default_from_email: "root@localhost"
  email_subject_prefix: "[Local Shop]"
cucumber:
  default_from_email: "root@localhost"
  email_subject_prefix: "[Local Shop]"
