development:
  enable_star: true
  min_prefix_len: 3
  max_matches: 100000
  mysql41: 9312
test:
  enable_star: true
  min_prefix_len: 3
  max_matches: 100000
  mysql41: 9313
cucumber:
  enable_star: true
  min_prefix_len: 3
  max_matches: 100000
  mysql41: 9313
production:
  enable_star: true
  min_prefix_len: 3
  max_matches: 100000
  mysql41: 9311
