development:
  min_prefix_len: 3
  mysql41: 9312
test:
  min_prefix_len: 3
  max_matches: 1000000
  mysql41: 9313
cucumber:
  min_prefix_len: 3
  max_matches: 1000000
  mysql41: 9313
production:
  min_prefix_len: 3
  max_matches: 1000000
  mysql41: 9311
